<?php
/**
 * Documentation Endpoint Controller
 */

namespace Simple_Documentation\Rest\V1;


class Documentation_Controller extends Simple_Documentation_Controller {

	public function register_routes() {
		$namespace = $this->get_namespace();
		$base = '/documentation';

		register_rest_route( $namespace, $base, [
			[
				'methods' => \WP_REST_Server::READABLE,
				'callback' => [ $this, 'get_items' ],
				'permission_callback' => [ $this, 'get_items_permissions_check' ],
				'args' => [],
			],
			[
				'methods' => \WP_REST_Server::CREATABLE,
				'callback' => [ $this, 'create_item' ],
				'permission_callback' => [ $this, 'create_item_permissions_check' ],
				'args' => $this->get_endpoint_args_for_item_schema( true ),
			],
		] );

		register_rest_route( $namespace, $base . '/(?P<id>[\d]+)', [
			[
				'methods' => \WP_REST_Server::READABLE,
				'callback' => [ $this, 'get_item' ],
				'permission_callback' => [ $this, 'get_item_permissions_check' ],
				'args' => [
					'context' => [
						'default' => 'view',
					],
				],
			],
			[
				'methods' => \WP_REST_Server::EDITABLE,
				'callback' => [ $this, 'update_item' ],
				'permission_callback' => [ $this, 'update_item_permissions_check' ],
				'args' => $this->get_endpoint_args_for_item_schema( false ),
			],
			[
				'methods' => \WP_REST_Server::DELETABLE,
				'callback' => [ $this, 'delete_item' ],
				'permission_callback' => [ $this, 'delete_item_permissions_check' ],
				'args' => [
					'force' => [
						'default' => false,
					],
				],
			],
		] );

		register_rest_route( $namespace, $base . '/schema', [
			'methods' => \WP_REST_Server::READABLE,
			'callback' => [ $this, 'get_public_item_schema' ],
		] );
	}

	public function get_items( $request ) {
		return parent::get_items( $request ); // TODO: Change the autogenerated stub
	}

	public function get_items_permissions_check( $request ) {
		return parent::get_items_permissions_check( $request ); // TODO: Change the autogenerated stub
	}

	public function create_item( $request ) {
		return parent::create_item( $request ); // TODO: Change the autogenerated stub
	}

	public function create_item_permissions_check( $request ) {
		return parent::create_item_permissions_check( $request ); // TODO: Change the autogenerated stub
	}

	public function get_item( $request ) {
		return parent::get_item( $request ); // TODO: Change the autogenerated stub
	}

	public function get_item_permissions_check( $request ) {
		return parent::get_item_permissions_check( $request ); // TODO: Change the autogenerated stub
	}

	public function update_item( $request ) {
		return parent::update_item( $request ); // TODO: Change the autogenerated stub
	}

	public function update_item_permissions_check( $request ) {
		return parent::update_item_permissions_check( $request ); // TODO: Change the autogenerated stub
	}

	public function delete_item( $request ) {
		return parent::delete_item( $request ); // TODO: Change the autogenerated stub
	}

	public function delete_item_permissions_check( $request ) {
		return parent::delete_item_permissions_check( $request ); // TODO: Change the autogenerated stub
	}
}
