<?php
/**
 * Simple Documentation Test Case
 */

abstract class SimpleDocumentation_UnitTestCase extends WP_UnitTestCase {
	public static function setUpBeforeClass() {
		return parent::setUpBeforeClass();
	}

	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function tearDown() {
		parent::tearDown(); // TODO: Change the autogenerated stub
	}


}
